version: '3.9'

services:

  app:
    image: bchkrvn/kr_5:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    restart: always

  nginx:
    image: nginx:1.20
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
